name: Sync file to Animate-telegramBot

on:
  push:
    paths:
      - "server/bot.js"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Push file to Animate-TelegramBot repo
        run: |
          git config --global user.name "Gokul Shaji"
          git config --global user.email "gokulshaji2005@gmail.com"
          git clone https://github.com/GokulShaji2005/Animate-telegramBot.git Bot
          cp server/bot.js Bot/
          cd Bot
          git add notes.txt
          git commit -m "Auto-sync notes.txt"
          git push https://<your-username>:${{ secrets.PERSONAL_TOKEN }}@github.com/<your-username>/<target-repo>.git main

