name: Sync file to Animate-telegramBot

on:
  push:
    paths:
      - "server/bot.js"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Push file to Animate-TelegramBot repo
        run: |
          git config --global user.name "Gokul Shaji"
          git config --global user.email "gokulshaji2005@gmail.com"
          git clone https://github.com/gokulShaji2005/Animate-telegramBot.git Bot
          cp server/bot.js Bot/
          cd Bot
          git add bot.js
          git commit -m "Auto-sync bot.js
          git push https://gokulshaji2005:${{ secrets.ANIMATE_TOKEN }}@github.com/gokulShaji2005/Animate-telegramBot.git main

